### PR TITLE
Remove submodules

### PR DESCRIPTION
**Pull request by lsoucasse**
This PR removes Janus and Mors as submodules and install them from PyPI instead as dependencies of the Proteus package. The version installed is specified in the pyproject.toml file.
Socrates is also deleted as a submodule. I used Harrison's script to get it from github and compile it. It thinks it is sufficient for now.

### CODE REVIEW

**Comment by nichollsh** [comment]
@lsoucasse please can you clarify for me what happens in the developer case?

If you clone JANUS and run `pip install -e .` on that package in your environment. Does this still satisfy the dependency in the PROTEUS `pyproject.toml` file? Or will it overwrite your local JANUS and install the version from pypi?

**Comment by lsoucasse** [comment]
> @lsoucasse please can you clarify for me what happens in the developer case?
> 
> Say you clone JANUS and run `pip install -e .` on that package in your environment. Does this still satisfy the dependency in the PROTEUS `pyproject.toml` file? Or will it overwrite your local JANUS and install the version from pypi?
> 
> Stef clarified a similar question previously ([#135 (comment)](https://github.com/FormingWorlds/PROTEUS/issues/135#issuecomment-2283425566)) but how does this change now that a particular release is specified in the pyproject file?



> @lsoucasse please can you clarify for me what happens in the developer case?
> 
> Say you clone JANUS and run `pip install -e .` on that package in your environment. Does this still satisfy the dependency in the PROTEUS `pyproject.toml` file? Or will it overwrite your local JANUS and install the version from pypi?
> 
> Stef clarified a similar question previously ([#135 (comment)](https://github.com/FormingWorlds/PROTEUS/issues/135#issuecomment-2283425566)) but how does this change now that a particular release is specified in the pyproject file?

Hi @nichollsh,
In this case I think what happens is that it will overwrite the PyPI install and proteus requirements will still be satisfied as long as the version number has not changed.
With changing version number we have to experiment, but you will always have the option to do pip uninstall/install locally to make sure which version you are actually using.

**Comment by nichollsh** [comment]
Okay, makes sense! Thanks

**Review by nichollsh — APPROVED** [review]
Looks good!

**Pull request merged**
