### PR TITLE
Add linting config and fix linting issues

### PR DESCRIPTION
**Pull request by stefsmeets**
This PR summarizes the changes made to master directly by accident last week:

- [Fix remaining issues](https://github.com/FormingWorlds/PROTEUS/commit/ebf502dc681f429054fbed02883d7d3e764da0bb)
- [Fix F841](https://github.com/FormingWorlds/PROTEUS/commit/b462fa7827f7d0b9ac83a966fc59c6af89b3216c)
- [Fix E701](https://github.com/FormingWorlds/PROTEUS/commit/a7959c296736b17a8ffc2274fd8624098f7963ac)
- [Fix F821](https://github.com/FormingWorlds/PROTEUS/commit/4a42a753078ccfcda9ae2e92468282fd76d5ccc2)
- [Apply ruff autofixes](https://github.com/FormingWorlds/PROTEUS/commit/5dc7fd25484bee034b6e8cc2d2bb0188c56edbea)
- [Update ruff config for linting](https://github.com/FormingWorlds/PROTEUS/commit/ebf502dc681f429054fbed02883d7d3e764da0bb)

I added a linting config, which will help catch a bunch of issues. See https://docs.astral.sh/ruff/rules/#pyflakes-f and https://docs.astral.sh/ruff/rules/#pycodestyle-e-w for more info.

I addressed many of the issues in the commits linked above. 

In addition, in this PR I made the final changes to get the linter to be happy.

These changes address #131 

## TODO:

- [x] Fix: Unexpected input(s) 'changed-files', valid inputs are ['args', 'src', 'version']

### CODE REVIEW

**Comment by stefsmeets** [comment]
@nichollsh Let me know what you think. If you are unhappy with any of the changes made to master, I can fix roll them back or fix them in this PR.

**Comment by nichollsh** [comment]
These changes look good! Is there a way to enforce a maximum line length of our choosing, rather than disabling the check entirely?

**Comment by stefsmeets** [comment]
Yeah, with `ruff --format`, but this will introduce a LOT of changes that I want to avoid in this PR.

**Comment by stefsmeets** [comment]
I think this PR is ready to be merged!

**Review by nichollsh — APPROVED** [review]

**Pull request merged**
