### PR TITLE
Generalise stellar wrapper, dummy star module

### LINKED ISSUE #202: Dummy star module
It would be useful to have a dummy module for stellar evolution, just as we have for the interior and atmosphere. This could be implemented alongside a generalised stellar wrapper.

This module could easily generate a stellar spectrum using a Planck function with a fixed stellar temperature. Setting the temperature to zero is equivalent to turning the star 'off'.

### PR DESCRIPTION
**Pull request by nichollsh**
This PR adds a dummy star module. It calculates the stellar spectrum and bolometric luminosity assuming that the star emits like a blackbody with a temperature and radius specified by the user. Added `dummy_star.toml` configuration to demonstrate this, but there isn't a test for this yet. Closes #202.

It also reworks the stellar module handling to generalise calculations between the mors and dummy modules. This mostly means moving functions into `src/proteus/star/` and calling these from `proteus.py`. This also meant moving a lot of variables in `proteus.py` into the `Proteus` class, which will also be useful for later work (e.g. #204, #162).

Minor things:
* Fixes numerical issue when volatile elemental inventory is small. Sometimes floating point errors mean that 0 kg of a given element can become ~1e-13 kg or so, which is problematic.
* Renamed `Lbol` config variable to `lum_now`, to make it clear that this is the *modern* luminosity of the star.
* Added `phys.py` for containing physics functions.
* Removed `start_proteus.py` since it is made redundant by the CLI.
* Fixes some of the deprecation warnings when accessing the config.

### CODE REVIEW

**Review by timlichtenberg — APPROVED** [review]
Looks good to me, but @lsoucasse should also give it a quick check.

**Review by lsoucasse — APPROVED** [review]
Nice changes! I will probably extend the baraffe_track property of proteus into a star_track to store either spada or baraffe data for the whole run.

The dummy star simulation seens to run fine on my laptop.

**Comment by nichollsh** [comment]
That makes sense - I guess this is covered by #134?

**Comment by nichollsh** [comment]
Thanks both!

**Pull request merged**
