### PR TITLE
Add cli doctor command

### LINKED ISSUE #240: Include warnings for user to update the code to modules latest versions
Hi, as I mentioned during the PROTEUS meeting this morning, proteus.py crashes when running the default configuration file:
$ proteus start --config input/default.toml
I 'git pulled' the main branch on my local computer to make sure I'm up to date, but it still crashes (see the proteus_00.log file attached for more details). The KeyError is "mass".

Let me know if you have any idea how to fix this :)

[proteus_00.log](https://github.com/user-attachments/files/17542430/proteus_00.log)

### PR DESCRIPTION
**Pull request by stefsmeets**
This PR adds a `proteus doctor` command that prints out potential updates to the modules. The latest versions are pulled from pypi or otherwise github.

Currently it checks:
- fwl-proteus
- fwl-mors
- fwl-calliope
- fwl-zephyrus
- aragog
- AGNI

Let me know if there is a need for more modules to be checked.

```console
$ proteus doctor
Dependencies
fwl-proteus: 404 Client Error: Not Found for url: https://pypi.org/pypi/fwl-proteus/json
fwl-mors: Update available 24.10.27 -> 24.11.18
fwl-calliope: ok
fwl-zephyrus: ok
aragog: Update available 0.1.0a0 -> 0.1.5a0
AGNI: No package metadata was found for AGNI is not installed.

Environment variables
FWL_DATA: Variable not set.
RAD_DIR: Variable not set.
```

Closes #240

### TODO

- [x] Add some documentation
- [x] Check for env variables

### CODE REVIEW

**Comment by stefsmeets** [comment]
Hi @timlichtenberg @nichollsh Let me know if this works for you and if there are any missing modules.

**Comment by nichollsh** [comment]
Also, it might be worth adding some information on this command to the documentation.

**Comment by nichollsh** [comment]
Makes sense. I'll drop the v from the GitHub tags.

**Comment by timlichtenberg** [comment]
Looks very usefu, thanks @stefsmeets! As a module to check, please add JANUS.

**Comment by stefsmeets** [comment]
@nichollsh @timlichtenberg This PR is ready. Let me know if you are happy with this, so that it can be merged!

@nichollsh I haven't stripped the 'v' from the agni version in this PR. This problem disappears once you make the next agni release.

**Review by nichollsh — APPROVED** [review]
Looks good! Thanks, Stef.

**Pull request merged**
