### PR TITLE
Minor updates for the documentation of the Kapteyn cluster section

### PR DESCRIPTION
**Pull request by EmmaPostolec**
Hi all, 
This is an update of the documentation on the Kapteyn cluster webpage (following issue https://github.com/FormingWorlds/PROTEUS/issues/271 ) . Following the discussion during the last PROTEUS meeting, I revised the Error reporting section, indicating now that the users should open an issue on the PROTEUS GitHub webpage. I also updated the NetCDF error display, so now it looks good.

I used the command ```pip install -e '.[docs]'``` and then ```mkdocs serve``` to compile it on my computer and be sure it displays as I want. (But the command ```pip install -e .[docs]``` without the ''worked to install the dependencies on the cluster, so I don't know if I should update the Contributing section about this ?)

Here I attached the old shared Google doc that @planetmariana, @nichollsh and I used to report problem while running PROTEUS on the cluster (created in April 2024). I think I mentioned all the relevant problems in the documentation webpage for the use of Kapteyn cluster. The other ones might be outdated with the new version of PROTEUS. Please let me know if you think I should include one of the point mentioned in the PDF so I can do it before merging. 

[Installation of PROTEUS on Kapteyn Cluster.pdf](https://github.com/user-attachments/files/18064490/Installation.of.PROTEUS.on.Kapteyn.Cluster.pdf)

### CODE REVIEW

**Review by lsoucasse — APPROVED** [review]
Looks good, thanks @EmmaPostolec

**Comment by EmmaPostolec** [comment]
Hi @lsoucasse, when I go to the documentation webpage it shows the previous version of the documentation (before this PR) but when I do ```mkdocs serve``` in my main branch (after I did ```git pull```) I can see the updated version of the documentation (after this PR). Do you have any idea on what should I do to fix this ? Thanks

**Comment by lsoucasse** [comment]
> Hi @lsoucasse, when I go to the documentation webpage it shows the previous version of the documentation (before this PR) but when I do `mkdocs serve` in my main branch (after I did `git pull`) I can see the updated version of the documentation (after this PR). Do you have any idea on what should I do to fix this ? Thanks :)

Hi @EmmaPostolec, for some reason the documentation built failed. It is automatically triggered when there is a merge in the main branch. I re-built it and now it works. I will send you an invite to be maintainer of the doc so that you can check the status and take action when necessary.

**Comment by lsoucasse** [comment]
Actually @EmmaPostolec , you first need to create an account on https://about.readthedocs.com/ , do a community log in with your github account.

**Comment by EmmaPostolec** [comment]
Hi @lsoucasse thanks a lot for re-building the doc and adding me as a maintainer on readthedocs ! :)

**Pull request merged**
