### PR TITLE
Remove config compatibility code

### LINKED ISSUE #245: Remove config compatibility layer.
All the config deprecation warnings have been fixed, so the compatibility layer can be removed.

Follow-up from #226

### PR DESCRIPTION
**Pull request by stefsmeets**
Closes #245

### CODE REVIEW

**Comment by stefsmeets** [comment]
Don't really need a hook to make releases on pypi. Good old `twine upload dist/*` still works fine 👍

**Comment by nichollsh** [comment]
@stefsmeets I am happy to review this once the `main` branch has been merged into this one and when the tests are passing.

**Comment by stefsmeets** [comment]
@nichollsh , I merged main so this can be reviewed 😁

**Comment by nichollsh** [comment]
Looks good - thanks @stefsmeets!

**Review by nichollsh — APPROVED** [review]

**Pull request merged**
