### PR TITLE
Set up automated tests via Github Actions

### LINKED ISSUE #86: Set up automated tests via Github Actions
Optimally, all newly introduced modules and functions should be automatically tested with every pull request. We will start to continuously work these in, also for older parts of the code that are not being tested as of yet.

See https://docs.github.com/en/actions.

Connected to: FormingWorlds/PROTEUS#71, FormingWorlds/PROTEUS#83

### PR DESCRIPTION
**Pull request by stefsmeets**
This PR sets up the boilerplate for automated tests on github. To avoid unnecessary tests (e.g. when the PR is not ready yet), I set it up so that the tests run after "Ready for review".

To run the tests locally: `pytest`
For now there is just a dummy `hello_world` function until we start to populate the proteus module.

I renamed `proteus.py` -> `start_proteus.py` to avoid a name collission with the module.

Closes #86

### CODE REVIEW

**Comment by stefsmeets** [comment]
@timlichtenberg

**Comment by stefsmeets** [comment]
@nichollsh This PR is ready, could you have a look at it?

**Comment by stefsmeets** [comment]
Snuck in a coverage badge while I have admin rights 😅

**Comment by timlichtenberg** [comment]
Currently the PROTEUS logo is not displayed correctly on the main Github page. Do you also want to fix this while at it?

**Review by nichollsh — APPROVED** [review]
Looks like a good start! It will be extremely useful to have some tests in PROTEUS, particularly as we transition to the new code structure.

**Pull request merged**
