### PR TITLE
Star wrapper consistency

### PR DESCRIPTION
**Pull request by lsoucasse**
This work restructures attributes of the star config and consistently uses Mors/Spada when this model is triggered.
- The config now better displays which parameters are used by what (dummy/mors) although this could be further refined between mors/baraffe and mors/spada
- When using Mors/Spada, the whole track (time evolution) data are generated for given star mass and rotation percentile and star properties (luminosity, radius, Teff) are computed from there.  Modern star properties for spectrum synthesis are also computed from the track which required little adaptation (and new release) of the mors package.
- These data are used consistently by the zephyrus escape model.

### CODE REVIEW

**Comment by lsoucasse** [comment]
This PR works together with Mors PR [here](https://github.com/FormingWorlds/MORS/pull/24).

The idea for the review is to approve the mors one first, then do a release and update proteus dependencies before merging this one.

**Comment by nichollsh** [comment]
Presumably you will need to re-run the tests on this one once merging the MORS changes. I can imagine that taking the 'modern' values from the tracks might yield different results compared to using the user-provided ones.

This is not to say it's wrong - I think it's more consistent - but maybe the test data will change.

**Review by nichollsh — APPROVED** [review]
Nice work - looks good. I think it's nice to unify the way the two tracks are treated. I agree with the way the input parameters have been re-organised. Does this change the status of #167?

Feel free to merge this once the MORS one is merged - the tests are passing on that branch now.

**Comment by lsoucasse** [comment]
> Presumably you will need to re-run the tests on this one once merging the MORS changes. I can imagine that taking the 'modern' values from the tracks might yield different results compared to using the user-provided ones.
> 
> This is not to say it's wrong - I think it's more consistent - but maybe the test data will change.

Thanks @nichollsh,

Actually the dummy test uses baraffe tracks so it will not be affected.  I ran the dummy test with spada data and got very similar results which gives some confidence in the implementation. Maybe worth to set a new test soon that uses spada data together with escape.

I am expecting little changes in the results with this new implementation. The individual euv flux values may change significantly in using the whole track, but we can hope that the ratios we are actually using are not. On the other hand, the bolometric flux is not altered.

**Comment by lsoucasse** [comment]
> Nice work - looks good. I think it's nice to unify the way the two tracks are treated. I agree with the way the input parameters have been re-organised. Does this change the status of #167?
> 
> Feel free to merge this once the MORS one is merged - the tests are passing on that branch now.

Yes it is closing the issue.

**Comment by lsoucasse** [comment]
Made a new Mors release and updated pyproject.toml requirements. Could you approve this again @nichollsh ?

**Review by nichollsh — APPROVED** [review]

**Pull request merged**
