### PR TITLE
Implement new config

### LINKED ISSUE #74: Rework configuration file
The current configuration file format is very confusing. It's not clear which parameters are necessary, and how they relate to each other. I've tried to make this clearer in the ReadTheDocs page using a table, but that's not good enough.

Since we want to keep things as "modules", which are swappable, I propose that we use a TOML file for the cfg format with a section for each module being used.

For example...

```
# Example cfg file with some arbitrary values

[runtime]
log_output =  true
output_folder = "path/to/folder"

[planet]
mass = 10.0
radius = 2.0
surface_bc = 2

[star]
mass = 1e5
radius = 1e4
spectrum = "path/to/file"

[modules]

    [modules.interior]
    enabled    = true
    selection  = "C_SPIDER"
    melt_curve = "path/to/file"

    [modules.atmosphere]
    enabled   = true
    selection = "JANUS"
   
        [modules.atmosphere.initial]
        use_params = false 
        H2O_bar    = 30.0

    [modules.escape]
    enabled   = false

```

See more info here: https://toml.io/en/
This connects with #62, #68, #66, #56, and #71.

### PR DESCRIPTION
**Pull request by stefsmeets**
This PR sets up the schema for the new config using [attrs](https://www.attrs.org/en/stable/index.html).

I made one change from the proposal, I changed `exec`->`params`, because exec is a reserved parameter in Python.

### Todo
- [x] Find way to store docstrings -> Although it is possible to store them on the attribute, this gets very cluttered. I suggest to pick this up in a follow-up PR and add them to the docstring.
- [x] Add more validators -> Follow-up in separate PR
- [x] Regenerate table for documentation -> Combine with docstring PR.
- [x] Convert older configs(?) -> Separate PR

Closes #74

### CODE REVIEW

**Comment by stefsmeets** [comment]
Hi @lsoucasse @nichollsh Could you have a look at this PR and let me know what you think?

I want to get this merged first to avoid ballooning this PR, and so that we have a baseline to work from. I will pick up other tasks (validation, documentation, integration) afterwards.

**Review by nichollsh — APPROVED** [review]
Looks like a good start! Thanks, Stef.

**Review by lsoucasse — APPROVED** [review]
Looks good, thanks! Now we have a clear separation between common options and module specific options.

I just think we should replace all atmos key by atmos_clim to be consistent with the repository structure and allow for future atmos_chem key for chemistry.

**Review by lsoucasse — APPROVED** [review]
Great!

**Pull request merged**
