### PR TITLE
Switch documentation over to mkdocs

### LINKED ISSUE #119: Move documentation to markdown
Just had a short chat with @lsoucasse , we discussed the idea of moving the documentation to markdown with mkdocs. See also the discussion in JANUS: https://github.com/FormingWorlds/JANUS/issues/29

### PR DESCRIPTION
**Pull request by stefsmeets**
This PR moves the documentation from rst/sphinx to markdown/mkdocs.

Example: https://proteus-code.readthedocs.io/en/mkdocs/

Closes #119

### TODO
- [x] Verify branch on readthedocs
- [x] Update slug to fwl-proteus

### CODE REVIEW

**Comment by stefsmeets** [comment]
@timlichtenberg

**Comment by timlichtenberg** [comment]
After that, I presume we should also change the URL of the docs to fwl-proteus, to homogenise it.

**Review by timlichtenberg — APPROVED** [review]
Great!

**Comment by stefsmeets** [comment]
> After that, I presume we should also change the URL of the docs to fwl-proteus, to homogenise it.

Makes sense, I will update the slug to fwl-proteus 👍

**Comment by stefsmeets** [comment]
Seems like readthedocs does not approve of updating the url: https://docs.readthedocs.io/en/stable/faq.html#how-do-i-change-my-project-slug-the-url-your-docs-are-served-at

**Review by timlichtenberg — APPROVED** [review]

**Pull request merged**
