### PR TITLE
Validate escape config

### LINKED ISSUE #286: Don't set escape level when escape is disabled
The current escape implementation will store the escape radius (R_xuv) and pressure (`P_xuv`) based on the atmosphere profiles determined by JANUS/AGNI. 

This is fine when escape is turned on, but it should not happen when escape is disabled, and instead these values should be set to the surface.

### PR DESCRIPTION
**Pull request by nichollsh**
Set `p_xuv` and `z_xuv` to surface when ZEPHYRUS is disabled. Closes #286 and https://github.com/FormingWorlds/PROTEUS/issues/258

Ensure that configuration uses MORS+Spada when ZEPHYRUS is enabled. Related to #232.

Avoid spurious values for `period` in first iteration. Calculation of this quantity depends on `M_star`, which is undefined when `period` is first calculated, and can cause some strange behaviour. Fixed this by ensuring that `M_star` is always defined.

### CODE REVIEW

**Review by EmmaPostolec — APPROVED** [review]
Hi Harrison, very nice job ! The condition on Pxuv computation is really nice to save some computational time. Also, very nice idea to create the get_heigh_from_pressure function, very effective. Thanks for introducing error message also for the user. The computation of mu in the orbit/wrapper.py is not really linked to this issue ?

**Comment by nichollsh** [comment]
Thanks Emma! The issue with mu is something that's slightly odd. I noticed that the tests *sometimes* fail with MacOS, even though they succeed on my PC. I think this is because of this `period` parameter being set by some undefined behaviour.

**Comment by EmmaPostolec** [comment]
Also I think this PR is linked to https://github.com/FormingWorlds/PROTEUS/issues/258 ?

**Comment by nichollsh** [comment]
Yes! It is. I didn't notice this issue, thanks Emma.

**Comment by EmmaPostolec** [comment]
No worries! I assigned myself this task but you did it faster than me :)

**Comment by lsoucasse** [comment]
I happy with these changes. You can merge them now Harrison so that I can update and merge my current PR afterwards.

**Comment by nichollsh** [comment]
Ah okay, sure! Thanks Laurent.

**Pull request merged**
