### PR TITLE
Plotting I/O improvements

### LINKED ISSUE #194: Improve plotting speed
Tests have found that `plot_iterfreq` - which sets how often the model should make plots - significant impacts performance. This is not only annoying, but potentially limits the number and resolution of the simulations, given finite resources.

We should optimise the plotting speed. This could be done by avoiding redundant reads/writes to the disk.

### PR DESCRIPTION
**Pull request by nichollsh**
Improvements to plotting speed at runtime by avoiding extra file reads. There are now common functions for reading NetCDF and JSON files from the disk. These are used to read the data into memory only once (or keep it in memory entirely for some cases), rather than having each plotting function individually read the data from the disk. Closes #194.

Note that the improvement scales with the number of data files to be read, and the frequency at which plotting is performed. We should still consider using larger `plot_iterfreq` values for further performance gains.

Should also make things easier when implementing Aragog, since we won't need to read files from the disk at all when making plots at runtime.

Also added some more instrument bandpasses for reference.

### CODE REVIEW

**Review by lsoucasse — APPROVED** [review]
Thanks Harrison, changes look OK.

I did not see any significant improvement on the running time though compared to previous implementation. Did you find some?

**Comment by nichollsh** [comment]
It doesn't make a difference to the dummy case because the plotting frequency is low, and it's not reading NetCDFS or JSON files anyway. When I ran some longer cases with JANUS, plotting every iteration, it reduced the runtime by between 5 and 10%.

**Comment by nichollsh** [comment]
Thanks for the review!

**Comment by lsoucasse** [comment]
> It doesn't make a difference to the dummy case because the plotting frequency is low, and it's not reading NetCDFS or JSON files anyway. When I ran some longer cases with JANUS, plotting every iteration, it reduced the runtime by between 5 and 10%. There's some variation depending on the number of model levels, and the the number of files it has to read.

Good to know. Thanks.

**Pull request merged**
